#ifndef GLOBAL_CONFIGURATION_IDS
#define GLOBAL_CONFIGURATION_IDS

enum GlobalConfiguration_IDs {
	CONFIGURATION_ID_MAIN_THREAD_SLEEP_MS = 0,
	CONFIGURATION_ID_AUTO_BLINK_ALERTER,
	CONFIGURATION_ID_AUTO_BLINK_ALERTER_MS,
};

#endif /* GLOBAL_CONFIGURATION_IDS */
