#ifndef GLOBAL_CONFIGURATION_IDS
#define GLOBAL_CONFIGURATION_IDS

enum GlobalConfiguration_IDs {
	CONFIGURATION_ID_MAIN_THREAD_SLEEP_US = 0,
	CONFIGURATION_ID_INPUT_THREAD_SLEEP_US,
	CONFIGURATION_ID_OUTPUT_THREAD_SLEEP_US,
	CONFIGURATION_ID_AUTO_BLINK_ALERTER,
	CONFIGURATION_ID_AUTO_BLINK_ALERTER_MS,
	CONFIGURATION_ID_MASZYNA_UART_CHECK_PACKET_RECEIVED,
};

#endif /* GLOBAL_CONFIGURATION_IDS */
