#include <limits.h>
#include "TrainConfiguration.h"
#include "TrainConfigurationIDs.h"
#include "Logger.h"

#define TRAIN_CONFIG_ENTRY(_id, _name, _min, _max, _init) \
	{ \
		.id = _id, \
		.name = _name, \
		.min_value = _min, \
		.max_value = _max, \
		.init_value = _init \
	}

#define TRAIN_CONFIG_ENTRY_2_STATE(_id, _name) TRAIN_CONFIG_ENTRY(_id, _name, 0, 1, 0)

struct Train_Configuration_Entry Train_Config[] = {
	TRAIN_CONFIG_ENTRY(CONFIGURATION_ID_HASLER_VELOCITY, "Train velocity", 0, 250, 0),
	TRAIN_CONFIG_ENTRY(CONFIGURATION_ID_ODOMETER, "Train odometer", 0, UINT_MAX, 0),
	TRAIN_CONFIG_ENTRY(CONFIGURATION_ID_VOLTMETER_LOW_VOLTAGE, "Voltometer low voltage", 0, 150, 0),
	TRAIN_CONFIG_ENTRY(CONFIGURATION_ID_VOLTMETER_HIGH_VOLTAGE, "Voltometer hight voltage", 0, 4000, 0),
	TRAIN_CONFIG_ENTRY(CONFIGURATION_ID_AMMETER_LOW_VOLTAGE, "Ammeter low voltage", 0, 120, 0),
	TRAIN_CONFIG_ENTRY(CONFIGURATION_ID_AMMETER_HIGH_VOLTAGE1, "Ammeter high voltage 1", 0, 800, 0),
	TRAIN_CONFIG_ENTRY(CONFIGURATION_ID_AMMETER_HIGH_VOLTAGE2, "Ammeter high voltage 2", 0, 800, 0),
	TRAIN_CONFIG_ENTRY(CONFIGURATION_ID_AMMETER_HIGH_VOLTAGE3, "Ammeter high voltage 3", 0, 800, 0),
	TRAIN_CONFIG_ENTRY(CONFIGURATION_ID_TANK_PRESSURE, "Tank pressure", 0, 1000, 0),
	TRAIN_CONFIG_ENTRY(CONFIGURATION_ID_PIPE_PRESSURE, "Pipe pressure", 0, 1000, 0),
	TRAIN_CONFIG_ENTRY(CONFIGURATION_ID_BREAK_PRESSURE, "Break pressure", 0, 1600, 0),
	TRAIN_CONFIG_ENTRY(CONFIGURATION_ID_PANTOGRAH_PRESSURE, "Panthograph pressure", 0, 1000, 0),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_INDICATOR_SHP, "SHP indicator"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_INDICATOR_ALERTER, "Alerter indicator"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_INDICATOR_BUZZER, "Buzzer indicator"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_INDICATOR_COMPRESSOR_OVERLOAD, "Compressor overload indicator"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_INDICATOR_VENTILATOR_OVERLOAD, "Ventilator overload indicator"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_INDICATOR_LINE_BREAKER, "Line breaker indicator"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_INDICATOR_TRACTION_ENGINE_OVERLOAD, "Traction engine overload indicator"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_INDICATOR_MAIN_CIRCUIT_DIFFERENTIAL, "Main circuit differential indicator"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_INDICATOR_CONVERTER_OVERLOAD, "Converter overload indicator"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_INDICATOR_LINE_CONTACTORS, "Line contactors indicator"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_INDICATOR_WHEELSLIP, "Wheelslip indicator"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_INDICATOR_HIGH_START, "High current start indicator"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_INDICATOR_RESTISTOR_RIDE, "Resistor ride indicator"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_INDICATOR_TRAIN_HEATING, "Train heating indicator"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_BUTTON_RESERVE, "Reserve button"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_BUTTON_COMPRESSOR_OVERLOAD_UNLOCK, "Compressor overload unlock button"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_BUTTON_LINE_BREAKER_DISABLE, "Line breaker disable button"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_BUTTON_LINE_BREAKER_ENABLE, "Line breaker enable button"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_BUTTON_TRACTION_ENGINE_OVERLOAD_UNLOCK, "Traction engine overload unlock button"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_BUTTON_CONVERTER_OVERLOAD_UNLOCK, "Converter overload unlock button"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_BUTTON_LINE_CONTACTORS_DISABLE, "Line contactors disable button"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_BUTTON_WHEELSLIP_COUNTER_ACTION, "Wheelsplip counter action button"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_BUTTON_RELAXER, "Break relaxer button"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_BUTTON_SHP_ALERTER_RESET, "SHP / Alerter reset button"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_SWITCH_BATTERY, "Battery switch"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_SWITCH_CABIN_ACTIVATION, "Cabin activation switch"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_SWITCH_LEGS_HEATING, "Legs heating switch"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_SWITCH_CABIN_LIGHT_DIMM, "Cabin light dimm switch"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_SWITCH_MEASURE_INSTRUMENT_LIGHT_DIMM, "Measure instrument light dimm switch"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_SWITCH_SIGNAL_LAMP1_DIMM, "Signal lamp 1 dimm switch"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_SWITCH_SIGNAL_LAMP2_DIMM, "Signal lamp 2 dimm switch"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_SWITCH_SIGNAL_LAMP_RED_LEFT, "Signal lamp red left switch"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_SWITCH_RESERVE, "Reserve switch"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_SWITCH_SIGNAL_LAMP_RED_RIGHT, "Signal lamp red right switch"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_SWITCH_MAIN_LIGHT, "Main light switch"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_SWITCH_CABIN_LIGHT, "Cabin light switch"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_SWITCH_MEASURE_INSTRUMENT_LIGHT, "Measure instrument light switch"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_SWITCH_HIGH_VOLTAGE_BOX_LIGHT, "High voltage box light switch"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_SWITCH_SIGNAL_LIGHT_LEFT, "Signal light left switch"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_SWITCH_SIGNAL_LIGHT_TOP, "Signal light top switch"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_SWITCH_SIGNAL_LIGHT_RIGHT, "Signal light right switch"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_SWITCH_SHP_INDICATOR_DIMM, "SHP indicator dimm switch"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_SWITCH_PANTHOGRAPH_A, "Panthograph A switch"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_SWITCH_COMPRESSOR, "Compressor switch"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_SWITCH_CONVERTER, "Converter switch"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_SWITCH_ALERTER_INDICATOR_DIMM, "Alerter indicator dimm switch"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_SWITCH_PANTHOGRAPH_B, "Panthograph B switch"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_SWITCH_TRAIN_HEATING, "Train heating switch"),
	TRAIN_CONFIG_ENTRY(CONFIGURATION_ID_SWITCH_BREAK_MODE, "Break mode switch", 0, 2, 0),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_SWITCH_WHEEL_PUSH_MODE, "Wheel push mode switch"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_SWITCH_VOLTAGE_RANGE_MODE, "Voltage range switch"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_SWITCH_SIGNAL_LIGHT1_DIMM, "Signal light 1 dimm switch"),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_SWITCH_SIGNAL_LIGHT2_DIMM, "Signal light 2 dimm switch"),
	TRAIN_CONFIG_ENTRY(CONFIGURATION_ID_SWITCH_WIPERS_MODE, "Wipers mode switch", 0, 3, 0),
	TRAIN_CONFIG_ENTRY_2_STATE(CONFIGURATION_ID_SWITCH_RADIO_ENABLE, "Radio enable switch"),
	TRAIN_CONFIG_ENTRY(CONFIGURATION_ID_SWITCH_RADIO_CHANNEL, "Radio channel switch", 0, 9, 0),
	TRAIN_CONFIG_ENTRY(CONFIGURATION_ID_CONTROLLER_TRAIN_DIRECTION, "Train direction controller", 0, 2, 0),
	TRAIN_CONFIG_ENTRY(CONFIGURATION_ID_CONTROLLER_ADJUSTER_WHEEL_POSITION, "Adjuster wheel controller position", 0, 43, 0),
	TRAIN_CONFIG_ENTRY(CONFIGURATION_ID_CONTROLLER_BYPASS_ACTUATOR_POSITION, "Bypass actuator controller position", 0, 6, 0),
	TRAIN_CONFIG_ENTRY(CONFIGURATION_ID_MAIN_BREAK_VALUE, "Main break value", 0, 1023, 0),
	TRAIN_CONFIG_ENTRY(CONFIGURATION_ID_LOC_BREAK_VALUE, "Locomotive break value", 0, 1023, 0),
};

TrainConfiguration::TrainConfiguration() : Configuration("Train Configuration")
{
	for (unsigned int i = 0; i < sizeof(Train_Config) / sizeof(struct Train_Configuration_Entry); i++) {
		ConfigurationEntry *e = new ConfigurationEntry(Train_Config[i].name, Train_Config[i].min_value,
				Train_Config[i].max_value, Train_Config[i].init_value);

		if (e != nullptr) {
			addConfigurationEntry(Train_Config[i].id, e);
		} else {
			log_error("Could not create configuration entry for [%s].\n", Train_Config[i].name);
		}
	}
}
