#ifndef VIRTUALCONTROL_TCPIP_H
#define VIRTUALCONTROL_TCPIP_H

#include "IController.h"
#include "TCPIP.h"
#include "Configuration.h"
#include "TrainConfigurationIDs.h"

#define VIRTUAL_CONTROL_TCPIP_CONFIGURATION_IDS_COUNT 54

class VirtualControlTCPIP : public IController {
	private:
		Configuration *conf;
		TCPIP *tcpip;

		const uint32_t configuration_ids[VIRTUAL_CONTROL_TCPIP_CONFIGURATION_IDS_COUNT] = {
			CONFIGURATION_ID_BUTTON_RESERVE,
			CONFIGURATION_ID_BUTTON_COMPRESSOR_OVERLOAD_UNLOCK,
			CONFIGURATION_ID_BUTTON_LINE_BREAKER_DISABLE,
			CONFIGURATION_ID_BUTTON_LINE_BREAKER_ENABLE,
			CONFIGURATION_ID_BUTTON_TRACTION_ENGINE_OVERLOAD_UNLOCK,
			CONFIGURATION_ID_BUTTON_CONVERTER_OVERLOAD_UNLOCK,
			CONFIGURATION_ID_BUTTON_LINE_CONTACTORS_DISABLE,
			CONFIGURATION_ID_BUTTON_WHEELSLIP_COUNTER_ACTION,
			CONFIGURATION_ID_BUTTON_RELAXER,
			CONFIGURATION_ID_BUTTON_SHP_ALERTER_RESET,
			CONFIGURATION_ID_BUTTON_SIREN_LOW,
			CONFIGURATION_ID_BUTTON_SIREN_HIGH,
			CONFIGURATION_ID_SWITCH_BATTERY,
			CONFIGURATION_ID_SWITCH_CABIN_ACTIVATION,
			CONFIGURATION_ID_SWITCH_LEGS_HEATING,
			CONFIGURATION_ID_SWITCH_CABIN_LIGHT_DIMM,
			CONFIGURATION_ID_SWITCH_MEASURE_INSTRUMENT_LIGHT_DIMM,
			CONFIGURATION_ID_SWITCH_SIGNAL_LAMP1_DIMM,
			CONFIGURATION_ID_SWITCH_SIGNAL_LAMP2_DIMM,
			CONFIGURATION_ID_SWITCH_SIGNAL_LAMP_RED_LEFT,
			CONFIGURATION_ID_SWITCH_RESERVE,
			CONFIGURATION_ID_SWITCH_SIGNAL_LAMP_RED_RIGHT,
			CONFIGURATION_ID_SWITCH_MAIN_LIGHT,
			CONFIGURATION_ID_SWITCH_CABIN_LIGHT,
			CONFIGURATION_ID_SWITCH_MEASURE_INSTRUMENT_LIGHT,
			CONFIGURATION_ID_SWITCH_HIGH_VOLTAGE_BOX_LIGHT,
			CONFIGURATION_ID_SWITCH_SIGNAL_LIGHT_LEFT,
			CONFIGURATION_ID_SWITCH_SIGNAL_LIGHT_TOP,
			CONFIGURATION_ID_SWITCH_SIGNAL_LIGHT_RIGHT,
			CONFIGURATION_ID_SWITCH_SHP_INDICATOR_DIMM,
			CONFIGURATION_ID_SWITCH_PANTHOGRAPH_A,
			CONFIGURATION_ID_SWITCH_COMPRESSOR,
			CONFIGURATION_ID_SWITCH_CONVERTER,
			CONFIGURATION_ID_SWITCH_ALERTER_INDICATOR_DIMM,
			CONFIGURATION_ID_SWITCH_PANTHOGRAPH_B,
			CONFIGURATION_ID_SWITCH_TRAIN_HEATING,
			CONFIGURATION_ID_SWITCH_BREAK_MODE,
			CONFIGURATION_ID_SWITCH_WHEEL_PUSH_MODE,
			CONFIGURATION_ID_SWITCH_VOLTAGE_RANGE_MODE,
			CONFIGURATION_ID_SWITCH_SIGNAL_LIGHT1_DIMM,
			CONFIGURATION_ID_SWITCH_SIGNAL_LIGHT2_DIMM,
			CONFIGURATION_ID_SWITCH_WIPERS_MODE,
			CONFIGURATION_ID_CONTROLLER_TRAIN_DIRECTION,
			CONFIGURATION_ID_CONTROLLER_ADJUSTER_WHEEL_POSITION,
			CONFIGURATION_ID_CONTROLLER_SHUNT_POSITION,
			CONFIGURATION_ID_MAIN_BREAK_VALUE,
			CONFIGURATION_ID_LOC_BREAK_VALUE,
			CONFIGURATION_ID_RADIO_SWITCH_ENABLE,
			CONFIGURATION_ID_RADIO_SWITCH_MICROPHONE_ENABLE,
			CONFIGURATION_ID_RADIO_BUTTON_RADIOSTOP,
			CONFIGURATION_ID_RADIO_BUTTON_EXT1,
			CONFIGURATION_ID_RADIO_BUTTON_EXT2,
			CONFIGURATION_ID_RADIO_BUTTON_EXT3,
			CONFIGURATION_ID_RADIO_SWITCH_CHANNEL
		};

		void writeTCPIP(void);

	public:
		VirtualControlTCPIP(TCPIP *tcpip, Configuration *conf);
		virtual ~VirtualControlTCPIP();

		virtual void sync(SyncDirection dir);
};

#endif /* VIRTUALCONTROL_TCPIP_H */
